global:
  resolve_timeout: 5m

route:
  receiver: 'email-notification'

receivers:
- name: 'email-notification'
  email_configs:
  - smarthost: 'smtp.gmail.com:587'
    from: 'krzysiek.kolodziej23@gmail.com'
    to: 'krzysiek.kolodziej23@gmail.com'
    auth_username: 'krzysiek.kolodziej23@gmail.com'
    auth_password: 'hxki hksg gkii rvij'
    send_resolved: true
    require_tls: true
    headers:
      subject: 'Prometheus Mail Alerts'

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'dev', 'instance']

