global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'apache_exporter'
    static_configs:
      - targets: ['apache_exporter:9117']
      
rule_files:
  - "/etc/prometheus/rules.yml"

alerting:
  alertmanagers:
  - api_version: v2
    enable_http2: True
    follow_redirects: True
    scheme: http
    timeout: 10s
    static_configs:
      - targets: ['alertmanager:9093']