global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'apache_exporter'
    static_configs:
      - targets: ['apache_exporter:9117']
      
rule_files:
  - "/etc/prometheus/rules.yml"