{
 "title": "Apache Metrics",
 "panels": [
  {
   "title": "Apache Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "apache_up", "legendFormat": "Apache Up" }
   ]
  },
  {
   "title": "Total Apache Accesses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "apache_accesses_total" }
   ]
  },
  {
   "title": "Apache CPU Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "apache_cpuload", "legendFormat": "CPU Load" }
   ]
  },
  {
   "title": "Apache Load (1m, 5m, 15m)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "apache_load{interval=\"1min\"}",
     "legendFormat": "1m Load"
    },
    {
     "expr": "apache_load{interval=\"5min\"}",
     "legendFormat": "5m Load"
    },
    {
     "expr": "apache_load{interval=\"15min\"}",
     "legendFormat": "15m Load"
    }
   ]
  }
 ]
}